version: '3.4'

services:
  php:
    build:
      context: ./docker/php
    networks:
      - pgnet
    volumes:
      - ./app:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  nginx:
    image: nginx:latest
    networks:
      - pgnet
    ports:
      - 8081:80
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

  postgres:
    image: postgres:13.3
    networks:
      - pgnet
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - 5435:5432
    volumes:
      - ./volumes/pgmaster/:/var/lib/postgresql/data
      - my-vol:/var/lib/postgresql/data

  redis:
    container_name: "redis"
    image: redis:7.2.3
    networks:
      - pgnet
    ports:
      - 6380:6379

  master:
    container_name: "citus_master"
    image: "citusdata/citus:12.1.3"
    networks:
      - pgnet
    ports: [ "5436:5432" ]
    labels: [ "com.citusdata.role=Master" ]
    environment: &AUTH
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: pwd
      PGUSER: "${POSTGRES_USER:-postgres}"
      PGPASSWORD: pwd
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"

  worker:
      image: "citusdata/citus:12.1.3"
      networks:
        - pgnet
      labels: [ "com.citusdata.role=Worker" ]
      depends_on: [ manager ]
      environment: *AUTH
      command: "/wait-for-manager.sh"
      volumes:
        - healthcheck-volume:/healthcheck

  manager:
      container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
      image: "citusdata/membership-manager:0.3.0"
      networks:
        - pgnet
      volumes:
        - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
        - healthcheck-volume:/healthcheck
      depends_on: [ master ]
      environment: *AUTH

volumes:
  my-vol:
  healthcheck-volume:
networks:
  pgnet:
